name: 'createScratchOrg'
description: 'Create the scratch org using the sent definition file'
author: 'Pablo Martinez'
runs:
  using: 'node16'
  main: './index.js'
inputs:
  scratch_definition_path:
    description: 'Path to the definition file that contains the Scratch org details'
    required: true
outputs:
  scratch_org_name:
    description: 'Name of the created scratch org.'    
branding:
  icon: 'file-plus'
  color: 'yellow'
